{% set name = "des-easyaccess" %}
{% set version = "1.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/des-labs/easyaccess/archive/refs/tags/{{ version }}.tar.gz
  sha256: cf59164f73d6c42959668238b3414d2a54f089c0d595f7284e0eef4e9d79b9e7
  patches:
    - version_patch.txt

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future >=0.15.0
    - requests
    - pandas >=0.14
    - termcolor >=1.1.0
    - fitsio >=1.0.5
    - cx_oracle
    - numpy >=1.19.2
    - setuptools

test:
  imports:
    - easyaccess
  commands:
    - easyaccess --help

about:
  home: https://github.com/des-labs/easyaccess
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: SQL command line interpreter for astronomical surveys
  description: |
    easyaccess is an enhanced command line interpreter and Python package
    created to facilitate access to astronomical catalogs stored in SQL
    Databases. It provides a custom interface with custom commands and was
    specifically designed to access data from the Dark Energy Survey Oracle
    database, including autocompletion of tables, columns, users and commands,
    simple ways to upload and download tables using csv, fits and HDF5 formats,
    iterators, search and description of tables among others. It can easily be
    extended to another surveys or SQL databases. The package was completely
    written in Python and support customized addition of commands and
    functionalities.
  dev_url: https://github.com/des-labs/easyaccess

extra:
  recipe-maintainers:
    - beckermr
